/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CatchAllRouteImport } from './routes/$catchAll'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlanetsIndexRouteImport } from './routes/planets/index'
import { Route as CharactersIndexRouteImport } from './routes/characters/index'
import { Route as PlanetIdIndexRouteImport } from './routes/planet/$id/index'
import { Route as CharacterIdIndexRouteImport } from './routes/character/$id/index'

const CatchAllRoute = CatchAllRouteImport.update({
  id: '/$catchAll',
  path: '/$catchAll',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanetsIndexRoute = PlanetsIndexRouteImport.update({
  id: '/planets/',
  path: '/planets/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIndexRoute = CharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanetIdIndexRoute = PlanetIdIndexRouteImport.update({
  id: '/planet/$id/',
  path: '/planet/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterIdIndexRoute = CharacterIdIndexRouteImport.update({
  id: '/character/$id/',
  path: '/character/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$catchAll': typeof CatchAllRoute
  '/characters/': typeof CharactersIndexRoute
  '/planets/': typeof PlanetsIndexRoute
  '/character/$id/': typeof CharacterIdIndexRoute
  '/planet/$id/': typeof PlanetIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$catchAll': typeof CatchAllRoute
  '/characters': typeof CharactersIndexRoute
  '/planets': typeof PlanetsIndexRoute
  '/character/$id': typeof CharacterIdIndexRoute
  '/planet/$id': typeof PlanetIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$catchAll': typeof CatchAllRoute
  '/characters/': typeof CharactersIndexRoute
  '/planets/': typeof PlanetsIndexRoute
  '/character/$id/': typeof CharacterIdIndexRoute
  '/planet/$id/': typeof PlanetIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$catchAll'
    | '/characters/'
    | '/planets/'
    | '/character/$id/'
    | '/planet/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$catchAll'
    | '/characters'
    | '/planets'
    | '/character/$id'
    | '/planet/$id'
  id:
    | '__root__'
    | '/'
    | '/$catchAll'
    | '/characters/'
    | '/planets/'
    | '/character/$id/'
    | '/planet/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatchAllRoute: typeof CatchAllRoute
  CharactersIndexRoute: typeof CharactersIndexRoute
  PlanetsIndexRoute: typeof PlanetsIndexRoute
  CharacterIdIndexRoute: typeof CharacterIdIndexRoute
  PlanetIdIndexRoute: typeof PlanetIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$catchAll': {
      id: '/$catchAll'
      path: '/$catchAll'
      fullPath: '/$catchAll'
      preLoaderRoute: typeof CatchAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planets/': {
      id: '/planets/'
      path: '/planets'
      fullPath: '/planets/'
      preLoaderRoute: typeof PlanetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/': {
      id: '/characters/'
      path: '/characters'
      fullPath: '/characters/'
      preLoaderRoute: typeof CharactersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planet/$id/': {
      id: '/planet/$id/'
      path: '/planet/$id'
      fullPath: '/planet/$id/'
      preLoaderRoute: typeof PlanetIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character/$id/': {
      id: '/character/$id/'
      path: '/character/$id'
      fullPath: '/character/$id/'
      preLoaderRoute: typeof CharacterIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatchAllRoute: CatchAllRoute,
  CharactersIndexRoute: CharactersIndexRoute,
  PlanetsIndexRoute: PlanetsIndexRoute,
  CharacterIdIndexRoute: CharacterIdIndexRoute,
  PlanetIdIndexRoute: PlanetIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
